# Generated by Django 6.0.1 on 2026-01-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("duree", models.PositiveIntegerField()),
                ("date_sortie", models.DateField()),
                ("genre", models.CharField(blank=True, max_length=100)),
                (
                    "affiche",
                    models.ImageField(blank=True, null=True, upload_to="affiches/"),
                ),
            ],
        ),
    ]
