# Generated by Django 6.0.1 on 2026-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Films", "0002_alter_film_description_alter_film_duree_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="date",
            new_name="date_reservation",
        ),
        migrations.AlterField(
            model_name="film",
            name="date_sortie",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="film",
            name="duree",
            field=models.PositiveIntegerField(help_text="Durée en minutes"),
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Drame", "Drame"),
                    ("Comédie", "Comédie"),
                    ("Horreur", "Horreur"),
                    ("Science-Fiction", "Science-Fiction"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="places",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
