# Generated by Django 6.0.1 on 2026-01-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Films", "0003_rename_date_reservation_date_reservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=5)),
                ("nb_lignes", models.PositiveIntegerField(default=5)),
                ("nb_colonnes", models.PositiveIntegerField(default=8)),
            ],
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="places",
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Drame", "Drame"),
                    ("Comédie", "Comédie"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Guerre", "Guerre"),
                    ("Science-Fiction", "Science-Fiction"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ligne", models.PositiveIntegerField()),
                ("colonne", models.PositiveIntegerField()),
                ("est_reserve", models.BooleanField(default=False)),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Films.salle"
                    ),
                ),
            ],
            options={
                "unique_together": {("salle", "ligne", "colonne")},
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="siege",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="Films.siege"
            ),
            preserve_default=False,
        ),
    ]
