# Generated by Django 6.0.1 on 2026-01-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Films", "0004_salle_remove_reservation_places_alter_film_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="film",
        ),
        migrations.RemoveField(
            model_name="siege",
            name="est_reserve",
        ),
        migrations.AlterField(
            model_name="film",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Action", "Action"),
                    ("Drame", "Drame"),
                    ("Comédie", "Comédie"),
                    ("Horreur", "Horreur"),
                    ("Romance", "Romance"),
                    ("Comédie musicale", "Comédie musicale"),
                    ("Guerre", "Guerre"),
                    ("Science-Fiction", "Science-Fiction"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salle",
            name="nom",
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances",
                        to="Films.film",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Films.salle"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="seance",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="Films.seance",
            ),
            preserve_default=False,
        ),
    ]
