# Generated by Django 6.0.1 on 2026-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Films", "0005_remove_reservation_film_remove_siege_est_reserve_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="siege",
        ),
        migrations.AddField(
            model_name="reservation",
            name="sieges",
            field=models.ManyToManyField(to="Films.siege"),
        ),
    ]
