# Generated by Django 6.0.1 on 2026-01-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Films", "0006_remove_reservation_siege_reservation_sieges"),
    ]

    operations = [
        migrations.AddField(
            model_name="siege",
            name="est_reserve",
            field=models.BooleanField(default=False),
        ),
    ]
